* Before Starting
 * Introductions
 * Please ask questions at any time.
 * instructor background
 * code of conduct
 * workshop operations (stickies? remote person somehow into group? split cohort into 2 x 3 groups?)
 * SQL is quite standard, everything you learn here today will have equivalents in other environments.
* Selecting Data
 * Mention tab completion
 * Mention =.schema= after lookng at =.table=
 * Mention =LIMIT= after showing =SELECT=
* Missing Values
 * mentioning =.nullvalue= would be useful at the start of this lesson.
* Creating and Modifying Data
 * Think about adding units to column names

* Looking forward
 * Different implementations
 * Stored Procedures
 * Extensions

* Issues we had (specific to this group)
 * The wide variety of skills and abilities of participants
 * Would have been better to group participants slightly differently;
   instructors were only able to adjust this day 2
   
 Issues that are addressable prior to next running of training
 * Not having enough unix skills
 * command line (not really knowing when they were in bash or sqlite, getting confused when sqlite3 commands weren't working in bash and visa versa)
 * fairly basic things like ls, cd, unzip could not really be relied on.
 * Could use a lesson of basic unix tools, like awk, sed grep, uniq, sort etc
 * familiarity and comfort with github was not great
 * R syntax such as library::function was not familiar
 * python was not familiar, it was the first time they were seeing jupyter notebooks
 * regex were not familiar
 * they had no working knowledge of pandas, and it would be useful to
   tie that knowledge in. Ideally use the same database they've
   already looked at (the mammals one) to do the querying and
   filtering in pandas (multiple ways of doing the same thing)
 * Quite a few times where we had assumed certain concepts had been
   covered and they had not e.g. wildcards in LIKE statements rely on
   using the same concept as .* from regular expressions or * from
   file globs and they didn't really have that underlying concept that
   we could reuse/build upon.
   
 Techinical issues
 * Technical issues with the server rstudio. We had issues where it
   would hang and we had to restart it. We had issues with copy and
   paste not working. 
 * Tab completion not working on the sliqte3 binary was very weird.
 * Library room was nice, worked fairly well. Remote participation
   actually worked reasonably well for most of the time, with only
   occasional audio issues.

